apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: oadp-operator
subjects:
  - kind: ServiceAccount
    name: oadp-operator
    namespace: "oadp-operator"
namespace: "oadp-operator"
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: oadp-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - security.openshift.io
  resources:
  - "*"
  verbs:
  - "*"

